"""The migration chain must actually run (and agree with the ORM models).

Every other test builds the schema with ``metadata.create_all`` and stubs Alembic out
(``conftest.py``), which is fast but means a broken revision reaches the user's database
before anyone notices — as one did: SQLite rewrites a table to alter a constraint ("batch"
mode) and refuses an unnamed one, so an autogenerated ``create_foreign_key(None, …)`` blew
up at startup. This test upgrades a throwaway database from zero to head and then asserts
autogenerate has nothing left to say.
"""

from __future__ import annotations

from argparse import Namespace
from pathlib import Path

from alembic import command
from alembic.autogenerate import compare_metadata
from alembic.config import Config
from alembic.migration import MigrationContext
from app.db_metadata import metadata
from sqlalchemy import create_engine

_ROOT = Path(__file__).resolve().parents[1]


def _config(db_url: str) -> Config:
    config = Config(str(_ROOT / "alembic.ini"))
    config.set_main_option("script_location", str(_ROOT / "alembic"))
    # env.py reads the URL from app settings unless one is passed as an -x argument.
    config.cmd_opts = Namespace(x=[f"url={db_url}"])
    return config


def test_migrations_run_from_scratch_to_head(tmp_path: Path) -> None:
    db_url = f"sqlite:///{(tmp_path / 'chain.db').as_posix()}"
    command.upgrade(_config(db_url), "head")

    engine = create_engine(db_url)
    with engine.connect() as conn:
        tables = set(MigrationContext.configure(conn).connection.dialect.get_table_names(conn))
    engine.dispose()
    # A few load-bearing tables from across the sprints.
    expected = {"entity", "domain_event", "quest", "npc", "npc_location_history", "map_region"}
    assert expected <= tables


def test_head_schema_matches_the_orm_models(tmp_path: Path) -> None:
    """Autogenerate must find no diff — i.e. no model landed without its migration."""
    db_url = f"sqlite:///{(tmp_path / 'head.db').as_posix()}"
    command.upgrade(_config(db_url), "head")

    engine = create_engine(db_url)
    with engine.connect() as conn:
        context = MigrationContext.configure(
            conn,
            opts={
                # FTS5 shadow tables are not ORM-managed (see alembic/env.py).
                "include_name": lambda name, type_, parent: not (
                    type_ == "table" and str(name).startswith("entity_fts")
                ),
            },
        )
        diff = compare_metadata(context, metadata)
    engine.dispose()

    assert diff == [], f"models and migrations disagree: {diff}"
