"""add_travel_scale_and_party_coords

Revision ID: 07dc0c8ea602
Revises: d7cf553578f2
Create Date: 2026-07-13 23:39:49.866586
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '07dc0c8ea602'
down_revision: str | None = 'd7cf553578f2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_connection',
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('from_location_id', sa.String(), nullable=False),
    sa.Column('to_location_id', sa.String(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('terrain', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_location_id'], ['entity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_location_id'], ['entity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('campaign_id', 'from_location_id', 'to_location_id')
    )
    with op.batch_alter_table('map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scale_pixels_per_unit', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('scale_unit', sa.String(), nullable=True))

    with op.batch_alter_table('party', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_map_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('current_x', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('current_y', sa.Float(), nullable=True))
        batch_op.create_foreign_key('fk_party_current_map_id', 'map', ['current_map_id'], ['entity_id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('party', schema=None) as batch_op:
        batch_op.drop_constraint('fk_party_current_map_id', type_='foreignkey')
        batch_op.drop_column('current_y')
        batch_op.drop_column('current_x')
        batch_op.drop_column('current_map_id')

    with op.batch_alter_table('map', schema=None) as batch_op:
        batch_op.drop_column('scale_unit')
        batch_op.drop_column('scale_pixels_per_unit')

    op.drop_table('location_connection')
    # ### end Alembic commands ###
