"""playbook combat_roll

Revision ID: 0a052984255d
Revises: f7a8b9c0d1e2
Create Date: 2026-07-16 14:33:13.484334
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0a052984255d'
down_revision: str | None = 'f7a8b9c0d1e2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('combat_roll',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('combat_run_id', sa.String(), nullable=False),
    sa.Column('combatant_id', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('expression', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('detail_json', sa.Text(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('target', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('recorded_at_real', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['combat_run_id'], ['combat_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('combat_roll', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_combat_roll_combat_run_id'), ['combat_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('combat_roll', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_combat_roll_combat_run_id'))

    op.drop_table('combat_roll')
    # ### end Alembic commands ###
