"""rules: stat_block

Revision ID: 1de74dad305b
Revises: e1a5d8bb8308
Create Date: 2026-07-09 06:37:51.511216
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '1de74dad305b'
down_revision: str | None = 'e1a5d8bb8308'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stat_block',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=True),
    sa.Column('rule_system_id', sa.String(), nullable=False),
    sa.Column('sheet_type', sa.String(), nullable=False),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('doc_json', sa.Text(), nullable=False),
    sa.Column('derived_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_system_id'], ['rule_system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stat_block', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stat_block_campaign_id'), ['campaign_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stat_block', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stat_block_campaign_id'))

    op.drop_table('stat_block')
    # ### end Alembic commands ###
