"""playbook: party and party_member

Revision ID: 269437a1bc81
Revises: f5d8de0fde26
Create Date: 2026-07-09 07:10:44.891574
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '269437a1bc81'
down_revision: str | None = 'f5d8de0fde26'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('party',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('gold', sa.Integer(), nullable=False),
    sa.Column('inventory_json', sa.Text(), nullable=False),
    sa.Column('reputation_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id')
    )
    op.create_table('party_member',
    sa.Column('party_id', sa.String(), nullable=False),
    sa.Column('stat_block_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status_json', sa.Text(), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stat_block_id'], ['stat_block.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('party_id', 'stat_block_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('party_member')
    op.drop_table('party')
    # ### end Alembic commands ###
