"""initial schema

Revision ID: 38e38e8dce57
Revises: 
Create Date: 2026-07-07 21:30:43.840874
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '38e38e8dce57'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_event',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('occurred_at_game', sa.Integer(), nullable=False),
    sa.Column('recorded_at_real', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('narrative_text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'seq', name='uq_event_campaign_seq')
    )
    with op.batch_alter_table('domain_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domain_event_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_domain_event_event_type'), ['event_type'], unique=False)

    op.create_table('rule_system',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('created_at_real', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('campaign',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rule_system_id', sa.String(), nullable=False),
    sa.Column('calendar_json', sa.Text(), nullable=False),
    sa.Column('clock_time_game', sa.Integer(), nullable=False),
    sa.Column('campaign_start_game', sa.Integer(), nullable=False),
    sa.Column('settings_json', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at_real', sa.String(), nullable=False),
    sa.Column('archived_at_real', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['rule_system_id'], ['rule_system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_member',
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('campaign_id', 'user_id')
    )
    op.create_table('entity',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('article_json', sa.Text(), nullable=True),
    sa.Column('article_text', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at_real', sa.String(), nullable=False),
    sa.Column('updated_at_real', sa.String(), nullable=False),
    sa.Column('deleted_at_real', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'slug', name='uq_entity_campaign_slug')
    )
    with op.batch_alter_table('entity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_campaign_id'), ['campaign_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_campaign_id'))

    op.drop_table('entity')
    op.drop_table('campaign_member')
    op.drop_table('campaign')
    op.drop_table('user')
    op.drop_table('rule_system')
    with op.batch_alter_table('domain_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domain_event_event_type'))
        batch_op.drop_index(batch_op.f('ix_domain_event_campaign_id'))

    op.drop_table('domain_event')
    # ### end Alembic commands ###
