"""playbook: combat_run and combat_action

Revision ID: 3da1686956df
Revises: 7788663fc6f7
Create Date: 2026-07-09 14:25:17.541026
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3da1686956df'
down_revision: str | None = '7788663fc6f7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('combat_run',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('encounter_id', sa.String(), nullable=True),
    sa.Column('started_at_game', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('fold_cursor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('combat_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_combat_run_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('combat_action',
    sa.Column('combat_run_id', sa.String(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('recorded_at_real', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['combat_run_id'], ['combat_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('combat_run_id', 'seq')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('combat_action')
    with op.batch_alter_table('combat_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_combat_run_campaign_id'))

    op.drop_table('combat_run')
    # ### end Alembic commands ###
