"""article snapshots

Revision ID: 447602cbf802
Revises: 2ec805391670
Create Date: 2026-07-10 10:14:33.848436
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '447602cbf802'
down_revision: str | None = '2ec805391670'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_snapshot',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('article_json', sa.Text(), nullable=False),
    sa.Column('preview', sa.String(), nullable=False),
    sa.Column('created_at_real', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_snapshot_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_snapshot_entity_id'), ['entity_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_snapshot_entity_id'))
        batch_op.drop_index(batch_op.f('ix_article_snapshot_campaign_id'))

    op.drop_table('article_snapshot')
    # ### end Alembic commands ###
