"""playbook: encounter

Revision ID: 7788663fc6f7
Revises: 269437a1bc81
Create Date: 2026-07-09 14:18:47.631886
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7788663fc6f7'
down_revision: str | None = '269437a1bc81'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encounter',
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('terrain', sa.String(), nullable=True),
    sa.Column('hazards', sa.Text(), nullable=True),
    sa.Column('tactics', sa.Text(), nullable=True),
    sa.Column('combatants_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    with op.batch_alter_table('encounter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_encounter_campaign_id'), ['campaign_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encounter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_encounter_campaign_id'))

    op.drop_table('encounter')
    # ### end Alembic commands ###
