"""quests + map regions

Revision ID: 9dd31e8e9a05
Revises: e840ca18d999
Create Date: 2026-07-10 00:42:32.094935
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9dd31e8e9a05'
down_revision: str | None = 'e840ca18d999'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quest',
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('quest_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('giver_npc_id', sa.String(), nullable=True),
    sa.Column('rewards_json', sa.Text(), nullable=False),
    sa.Column('deadline_game', sa.Integer(), nullable=True),
    sa.Column('objectives_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['giver_npc_id'], ['entity.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    with op.batch_alter_table('quest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quest_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('map_region',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('map_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('polygon_json', sa.Text(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('target_entity_id', sa.String(), nullable=True),
    sa.Column('child_map_id', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('layer', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['child_map_id'], ['map.entity_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['map_id'], ['map.entity_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entity.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('map_region', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_map_region_map_id'), ['map_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map_region', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_map_region_map_id'))

    op.drop_table('map_region')
    with op.batch_alter_table('quest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quest_campaign_id'))

    op.drop_table('quest')
    # ### end Alembic commands ###
