"""campaign realtime clock fields

Revision ID: a852c53ddd91
Revises: 3da1686956df
Create Date: 2026-07-09 14:52:55.388936
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a852c53ddd91'
down_revision: str | None = '3da1686956df'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('realtime_enabled', sa.Integer(), nullable=False, server_default='0')
        )
        batch_op.add_column(sa.Column('realtime_anchor_real', sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column('realtime_paused', sa.Integer(), nullable=False, server_default='0')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_column('realtime_paused')
        batch_op.drop_column('realtime_anchor_real')
        batch_op.drop_column('realtime_enabled')

    # ### end Alembic commands ###
