"""links: link_type and link

Revision ID: cca2652c918f
Revises: 3fc7e15f8773
Create Date: 2026-07-08 07:43:24.032354
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'cca2652c918f'
down_revision: str | None = '3fc7e15f8773'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_type',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('inverse_label', sa.String(), nullable=False),
    sa.Column('is_semantic', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('link',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('from_entity', sa.String(), nullable=False),
    sa.Column('to_entity', sa.String(), nullable=False),
    sa.Column('link_type_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('valid_from_game', sa.Integer(), nullable=True),
    sa.Column('valid_to_game', sa.Integer(), nullable=True),
    sa.Column('created_at_real', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_entity'], ['entity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_type_id'], ['link_type.id'], ),
    sa.ForeignKeyConstraint(['to_entity'], ['entity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_entity', 'to_entity', 'link_type_id', 'source', name='uq_link_edge')
    )
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_link_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_link_from_entity'), ['from_entity'], unique=False)
        batch_op.create_index(batch_op.f('ix_link_to_entity'), ['to_entity'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_link_to_entity'))
        batch_op.drop_index(batch_op.f('ix_link_from_entity'))
        batch_op.drop_index(batch_op.f('ix_link_campaign_id'))

    op.drop_table('link')
    op.drop_table('link_type')
    # ### end Alembic commands ###
