"""npc dynamics: npc, location history, schedules

Revision ID: cd9294f53ab3
Revises: 9dd31e8e9a05
Create Date: 2026-07-10 06:52:04.746649
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'cd9294f53ab3'
down_revision: str | None = '9dd31e8e9a05'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('npc',
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_location_id', sa.String(), nullable=True),
    sa.Column('has_met_party', sa.Integer(), nullable=False),
    sa.Column('last_party_interaction_game', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('secrets', sa.Text(), nullable=True),
    sa.Column('voice_notes', sa.Text(), nullable=True),
    sa.Column('stat_block_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_location_id'], ['entity.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stat_block_id'], ['stat_block.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    with op.batch_alter_table('npc', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_npc_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_npc_current_location_id'), ['current_location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_npc_status'), ['status'], unique=False)

    op.create_table('npc_location_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('npc_id', sa.String(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=True),
    sa.Column('from_game', sa.Integer(), nullable=False),
    sa.Column('to_game', sa.Integer(), nullable=True),
    sa.Column('cause_event_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['entity.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['npc_id'], ['entity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('npc_location_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_npc_location_history_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_npc_location_history_npc_id'), ['npc_id'], unique=False)

    op.create_table('npc_schedule',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('npc_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('rule_json', sa.Text(), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.Column('materialized_through_game', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['npc_id'], ['entity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('npc_schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_npc_schedule_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_npc_schedule_npc_id'), ['npc_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('npc_schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_npc_schedule_npc_id'))
        batch_op.drop_index(batch_op.f('ix_npc_schedule_campaign_id'))

    op.drop_table('npc_schedule')
    with op.batch_alter_table('npc_location_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_npc_location_history_npc_id'))
        batch_op.drop_index(batch_op.f('ix_npc_location_history_campaign_id'))

    op.drop_table('npc_location_history')
    with op.batch_alter_table('npc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_npc_status'))
        batch_op.drop_index(batch_op.f('ix_npc_current_location_id'))
        batch_op.drop_index(batch_op.f('ix_npc_campaign_id'))

    op.drop_table('npc')
    # ### end Alembic commands ###
