"""add_description_to_scheduled_event

Revision ID: d7cf553578f2
Revises: d4e2b7c91a05
Create Date: 2026-07-13 20:15:44.374769
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd7cf553578f2'
down_revision: str | None = 'd4e2b7c91a05'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_event', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
