"""chronicle: timeline, sessions, event subjects

Revision ID: e1a5d8bb8308
Revises: 9a7c1cab5430
Create Date: 2026-07-08 20:46:08.707642
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e1a5d8bb8308'
down_revision: str | None = '9a7c1cab5430'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('real_date', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('clock_start_game', sa.Integer(), nullable=True),
    sa.Column('clock_end_game', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'session_number', name='uq_session_campaign_number')
    )
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('timeline_entry',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('occurred_at_game', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('significance', sa.Integer(), nullable=False),
    sa.Column('is_hidden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['domain_event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timeline_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timeline_entry_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_timeline_entry_occurred_at_game'), ['occurred_at_game'], unique=False)

    op.create_table('timeline_entity',
    sa.Column('timeline_id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['timeline_id'], ['timeline_entry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('timeline_id', 'entity_id')
    )
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_session_id', sa.String(), nullable=True))

    with op.batch_alter_table('domain_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_entity_ids_json', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domain_event', schema=None) as batch_op:
        batch_op.drop_column('subject_entity_ids_json')

    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_column('current_session_id')

    op.drop_table('timeline_entity')
    with op.batch_alter_table('timeline_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timeline_entry_occurred_at_game'))
        batch_op.drop_index(batch_op.f('ix_timeline_entry_campaign_id'))

    op.drop_table('timeline_entry')
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_campaign_id'))

    op.drop_table('session')
    # ### end Alembic commands ###
