"""story: story_node and story_edge

Revision ID: e1b152f089e5
Revises: 447602cbf802
Create Date: 2026-07-11 08:55:32.583381
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e1b152f089e5'
down_revision: str | None = '447602cbf802'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_node',
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('pos_x', sa.Float(), nullable=False),
    sa.Column('pos_y', sa.Float(), nullable=False),
    sa.Column('consequences_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    with op.batch_alter_table('story_node', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_story_node_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('story_edge',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('from_node', sa.String(), nullable=False),
    sa.Column('to_node', sa.String(), nullable=False),
    sa.Column('condition_expr', sa.Text(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_node'], ['story_node.entity_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_node'], ['story_node.entity_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('story_edge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_story_edge_campaign_id'), ['campaign_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story_edge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_story_edge_campaign_id'))

    op.drop_table('story_edge')
    with op.batch_alter_table('story_node', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_story_node_campaign_id'))

    op.drop_table('story_node')
    # ### end Alembic commands ###
