"""atlas: media, map, map_marker

Revision ID: e840ca18d999
Revises: a852c53ddd91
Create Date: 2026-07-09 20:07:10.384688
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e840ca18d999'
down_revision: str | None = 'a852c53ddd91'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('mime', sa.String(), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('created_at_real', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('map',
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('media_id', sa.String(), nullable=False),
    sa.Column('width_px', sa.Integer(), nullable=False),
    sa.Column('height_px', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=True),
    sa.Column('parent_map_id', sa.String(), nullable=True),
    sa.Column('map_kind', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['entity.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['parent_map_id'], ['map.entity_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    with op.batch_alter_table('map', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_map_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('map_marker',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('map_id', sa.String(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('target_entity_id', sa.String(), nullable=True),
    sa.Column('child_map_id', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('layer', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['child_map_id'], ['map.entity_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['map_id'], ['map.entity_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entity.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('map_marker', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_map_marker_map_id'), ['map_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map_marker', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_map_marker_map_id'))

    op.drop_table('map_marker')
    with op.batch_alter_table('map', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_map_campaign_id'))

    op.drop_table('map')
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_campaign_id'))

    op.drop_table('media')
    # ### end Alembic commands ###
