"""rules: monster bestiary

Revision ID: f5d8de0fde26
Revises: 1de74dad305b
Create Date: 2026-07-09 07:03:26.713851
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f5d8de0fde26'
down_revision: str | None = '1de74dad305b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monster',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('stat_block_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('variant_of', sa.String(), nullable=True),
    sa.Column('facet1_num', sa.Float(), nullable=True),
    sa.Column('facet2_num', sa.Float(), nullable=True),
    sa.Column('facet1_text', sa.String(), nullable=True),
    sa.Column('facet2_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stat_block_id'], ['stat_block.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_of'], ['monster.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monster', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monster_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index('ix_monster_facets', ['campaign_id', 'facet1_num', 'facet1_text'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monster', schema=None) as batch_op:
        batch_op.drop_index('ix_monster_facets')
        batch_op.drop_index(batch_op.f('ix_monster_campaign_id'))

    op.drop_table('monster')
    # ### end Alembic commands ###
